apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-consumer
  namespace: default # замена
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-consumer
  template:
    metadata:
      labels:
        app: web-consumer
    spec:
      containers:
      - command:
        - sh
        - -c
        # Теперь сервис auth-db будет найден, т.к. находится в том же namespace
        - while true; do curl -s http://auth-db; sleep 5; done
        image: curlimages/curl:latest
        name: curl-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: default # замена
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - image: nginx:1.19.1
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: default # замена
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:

    app: auth-db
